# Generated by Django 5.2.9 on 2025-12-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='_'),
            preserve_default=False,
        ),
    ]
