# Generated by Django 5.2.9 on 2025-12-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_customer_store_custo_second__f07c56_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
    ]
