# Generated by Django 5.2.9 on 2025-12-29 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('production_summary', 'Production Summary'), ('quality_grading', 'Quality Grading'), ('order_performance', 'Order Performance')], max_length=50, unique=True)),
                ('last_generated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
