# Generated by Django 5.1.6 on 2026-01-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order_productionorder_qualitygrading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ProductionOrder',
        ),
        migrations.DeleteModel(
            name='QualityGrading',
        ),
    ]
